version: "3.3" 

services:
  app:
    image: egoexpress/weechat
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "113:113"
    volumes:
      - data:/weechat
    environment:
      - 'GID=1000'
      - 'UID=100'

  identd:
    image: egoexpress/nullidentd
    network_mode: "service:app"
    environment:
      - IDENT_USER=unknown

volumes:
  data:
