version: "3.3" 

services:
  weechat:
    image: jkaberg/weechat
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "113:113"
    volumes:
      - weechat:/weechat
    environment:
      - 'GID=1000'
      - 'UID=100'

  identd:
    image: egoexpress/nullidentd
    network_mode: "service:weechat" 
    environment:
      - IDENT_USER=unknown

volumes:
  weechat:
